{{- if .Values.monitoring.alertmanager.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flexfit.fullname" . }}-alertmanager
  labels:
    {{- include "flexfit.labels" . | nindent 4 }}
    app.kubernetes.io/component: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "flexfit.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: alertmanager
  template:
    metadata:
      labels:
        {{- include "flexfit.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: "{{ .Values.monitoring.alertmanager.image.repository }}:{{ .Values.monitoring.alertmanager.image.tag }}"
        imagePullPolicy: {{ .Values.monitoring.alertmanager.image.pullPolicy | default "IfNotPresent" }}
        ports:
        - name: http
          containerPort: 9093
          protocol: TCP
        env:
        - name: SMTP_HOST
          value: "{{ .Values.monitoring.alerts.email.smtpHost | default "smtp.gmail.com:587" }}"
        - name: ALERT_EMAIL_FROM
          value: "{{ .Values.monitoring.alerts.email.from | default "hakanduranyt@gmail.com" }}"
        - name: ALERT_EMAIL_TO
          value: "{{ .Values.monitoring.alerts.email.to | default "hakanduranyt@gmail.com" }}"
        - name: ALERT_EMAIL_USERNAME
          value: "{{ .Values.monitoring.alerts.email.username | default "hakanduranyt@gmail.com" }}"
        - name: ALERT_EMAIL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "flexfit.fullname" . }}-secrets
              key: ALERT_EMAIL_PASSWORD
        command: 
        - /bin/sh
        - -c
        - |
          # Install envsubst if not available
          if ! command -v envsubst > /dev/null 2>&1; then
              apk add --no-cache gettext
          fi
          
          # Process config with environment variables
          envsubst < /etc/alertmanager/alertmanager.yml > /tmp/alertmanager.yml
          
          # Start Alertmanager
          exec /bin/alertmanager \
              --config.file=/tmp/alertmanager.yml \
              --storage.path=/alertmanager \
              --web.external-url=http://localhost:9093
        volumeMounts:
        - name: alertmanager-config
          mountPath: /etc/alertmanager
        - name: alertmanager-storage
          mountPath: /alertmanager
        resources:
          {{- toYaml (.Values.monitoring.alertmanager.resources | default .Values.resources) | nindent 10 }}
      volumes:
      - name: alertmanager-config
        configMap:
          name: {{ include "flexfit.fullname" . }}-alertmanager-config
      - name: alertmanager-storage
        emptyDir: {}
{{- end }} 