apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ include "flexfit.namespace" . }}
  labels:
    app: frontend
    {{- include "flexfit.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: frontend