apiVersion: v1
kind: Service
metadata:
  name: {{ include "flexfit.fullname" . }}-genai-worker-local
  labels:
    {{- include "flexfit.labels" . | nindent 4 }}
    app.kubernetes.io/component: genai-worker-local
spec:
  type: {{ .Values.genaiWorkerLocal.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.genaiWorkerLocal.service.port | default 8084 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "flexfit.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: genai-worker-local 