apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ include "flexfit.namespace" . }}
  labels:
    app: postgres
    {{- include "flexfit.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: postgres