{{- if .Values.monitoring.prometheus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flexfit.fullname" . }}-prometheus-config
  labels:
    {{- include "flexfit.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    rule_files:
      - "/etc/prometheus/alert_rules.yml"

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - flexfit-alertmanager:9093

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'flexfit-services'
        static_configs:
          - targets: 
            - 'service-registry:8761'
            - 'api-gateway:8080'
            - 'user-service:8081'
            - 'workout-plan-service:8082'
        metrics_path: '/actuator/prometheus'
        scrape_interval: 15s

      - job_name: 'flexfit-genai'
        static_configs:
          - targets:
            - 'genai-worker:8083'
            - 'flexfit-genai-worker-local:8084'
        metrics_path: '/metrics'
        scrape_interval: 15s

      - job_name: 'postgres'
        static_configs:
          - targets: ['postgres:5432']
        scrape_interval: 30s

  alert_rules.yml: |
    groups:
      - name: flexfit-alerts
        rules:
          - alert: ServiceDown
            expr: up == 0
            for: 2m
            labels:
              severity: critical
            annotations:
              summary: "Service {{`{{ $labels.instance }}`}} is down"
              description: "{{`{{ $labels.instance }}`}} has been down for more than 2 minutes."

          - alert: HighErrorRate
            expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High error rate on {{`{{ $labels.instance }}`}}"
              description: "Error rate is {{`{{ $value }}`}} requests per second."

          - alert: HighMemoryUsage
            expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 80
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High memory usage on {{`{{ $labels.instance }}`}}"
              description: "Memory usage is above 80%"
{{- end }} 