apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ include "flexfit.namespace" . }}
  labels:
    {{- include "flexfit.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.postgres.password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: chair-api-secret
  namespace: {{ include "flexfit.namespace" . }}
  labels:
    {{- include "flexfit.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.chairApiKey | b64enc | quote }}