apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flexfit.fullname" . }}-secrets
  namespace: {{ include "flexfit.namespace" . }}
  labels:
    {{- include "flexfit.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc | quote }}
  CHAIR_API_KEY: {{ .Values.chairApiKey | b64enc | quote }}
  {{- if .Values.monitoring.alerts.email.enabled }}
  ALERT_EMAIL_PASSWORD: {{ .Values.monitoring.alerts.email.password | b64enc | quote }}
  {{- end }}