apiVersion: v1
kind: Service
metadata:
  name: service-registry
  namespace: {{ include "flexfit.namespace" . }}
  labels:
    app: service-registry
    {{- include "flexfit.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceRegistry.service.type }}
  ports:
  - port: {{ .Values.serviceRegistry.service.port }}
    targetPort: 8761
    protocol: TCP
    name: http
  selector:
    app: service-registry