apiVersion: v1
kind: Service
metadata:
  name: {{ include "flexfit.fullname" . }}-tts-service
  labels:
    {{- include "flexfit.labels" . | nindent 4 }}
    app.kubernetes.io/component: tts-service
spec:
  type: ClusterIP
  ports:
    - port: 8083
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "flexfit.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: tts-service 