apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: {{ include "flexfit.namespace" . }}
  labels:
    app: user-service
    {{- include "flexfit.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.userService.replicaCount }}
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: "{{ .Values.userService.image.repository }}:{{ .Values.userService.image.tag }}"
        imagePullPolicy: {{ .Values.userService.image.pullPolicy }}
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://service-registry:8761/eureka/"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres:5432/flexfit"
        - name: SPRING_DATASOURCE_USERNAME
          value: "flexfit"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        {{- range .Values.userService.env }}
        - name: {{ .name }}
          value: "{{ .value }}"
        {{- end }}
        resources:
          limits:
            cpu: {{ .Values.userService.resources.limits.cpu }}
            memory: {{ .Values.userService.resources.limits.memory }}
          requests:
            cpu: {{ .Values.userService.resources.requests.cpu }}
            memory: {{ .Values.userService.resources.requests.memory }}
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 120
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 90
          periodSeconds: 10