apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: {{ include "flexfit.namespace" . }}
  labels:
    app: user-service
    {{- include "flexfit.labels" . | nindent 4 }}
spec:
  type: {{ .Values.userService.service.type }}
  ports:
  - port: {{ .Values.userService.service.port }}
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: user-service