apiVersion: v1
kind: Service
metadata:
  name: workout-plan-service
  namespace: {{ include "flexfit.namespace" . }}
  labels:
    app: workout-plan-service
    {{- include "flexfit.labels" . | nindent 4 }}
spec:
  type: {{ .Values.workoutPlanService.service.type }}
  ports:
  - port: {{ .Values.workoutPlanService.service.port }}
    targetPort: 8082
    protocol: TCP
    name: http
  selector:
    app: workout-plan-service