version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:13
    container_name: flexfit-db
    environment:
      - POSTGRES_DB=flexfit
      - POSTGRES_USER=flexfit
      - POSTGRES_PASSWORD=flexfit123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flexfit-network

  # Eureka Service Registry
  service-registry:
    build: ./server/service-registry
    container_name: flexfit-service-registry
    ports:
      - "8761:8761"
    networks:
      - flexfit-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # API Gateway
  api-gateway:
    build: ./server/api-gateway
    container_name: flexfit-api-gateway
    ports:
      - "8080:8000"
    depends_on:
      - service-registry
    networks:
      - flexfit-network
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-registry:8761/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # User Service
  user-service:
    build: ./server/user-service
    container_name: flexfit-user-service
    depends_on:
      - db
      - service-registry
    networks:
      - flexfit-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/flexfit
      - SPRING_DATASOURCE_USERNAME=flexfit
      - SPRING_DATASOURCE_PASSWORD=flexfit123
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-registry:8761/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Workout Plan Service
  workout-plan-service:
    build: ./server/workout-plan-service
    container_name: flexfit-workout-plan-service
    depends_on:
      - db
      - service-registry
    networks:
      - flexfit-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/flexfit
      - SPRING_DATASOURCE_USERNAME=flexfit
      - SPRING_DATASOURCE_PASSWORD=flexfit123
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-registry:8761/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # TTS Service
  tts-service:
    build: ./server/tts-service
    container_name: flexfit-tts-service
    ports:
      - "8083:8083"
    depends_on:
      - service-registry
    networks:
      - flexfit-network
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-registry:8761/eureka
      - GOOGLE_APPLICATION_CREDENTIALS_JSON=${GOOGLE_APPLICATION_CREDENTIALS_JSON}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/api/tts/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # GenAI Workout Worker (Open WebUI)
  genai-workout-worker:
    build: ./genai
    container_name: flexfit-genai-worker
    ports:
      - "8000:8000"
    networks:
      - flexfit-network
    environment:
      # Open WebUI Configuration
      - OPEN_WEBUI_BASE_URL=https://gpu.aet.cit.tum.de
      - CHAIR_API_KEY=${CHAIR_API_KEY}
      - MODEL_NAME=${MODEL_NAME}
      # - MOCK_MODE=true  # Enable for faster testing
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Next.js Frontend
  frontend:
    build: ./client
    container_name: flexfit-frontend
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
    networks:
      - flexfit-network
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  flexfit-network:
    driver: bridge

volumes:
  postgres_data: