# Production docker-compose using GitHub Container Registry images
version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:13
    container_name: flexfit-db
    environment:
      - POSTGRES_DB=flexfit
      - POSTGRES_USER=flexfit
      - POSTGRES_PASSWORD=${DB_PASSWORD:-flexfit123}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flexfit-network
    restart: unless-stopped

  # Eureka Service Registry
  service-registry:
    image: ghcr.io/aet-devops25/team-code-compass/service-registry:${IMAGE_TAG:-latest}
    container_name: flexfit-service-registry
    ports:
      - "8761:8761"
    networks:
      - flexfit-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # API Gateway
  api-gateway:
    image: ghcr.io/aet-devops25/team-code-compass/api-gateway:${IMAGE_TAG:-latest}
    container_name: flexfit-api-gateway
    ports:
      - "8080:8000"
    depends_on:
      - service-registry
    networks:
      - flexfit-network
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-registry:8761/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # User Service
  user-service:
    image: ghcr.io/aet-devops25/team-code-compass/user-service:${IMAGE_TAG:-latest}
    container_name: flexfit-user-service
    depends_on:
      - db
      - service-registry
    networks:
      - flexfit-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/flexfit
      - SPRING_DATASOURCE_USERNAME=flexfit
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD:-flexfit123}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-registry:8761/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Workout Plan Service
  workout-plan-service:
    image: ghcr.io/aet-devops25/team-code-compass/workout-plan-service:${IMAGE_TAG:-latest}
    container_name: flexfit-workout-plan-service
    depends_on:
      - db
      - service-registry
    networks:
      - flexfit-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/flexfit
      - SPRING_DATASOURCE_USERNAME=flexfit
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD:-flexfit123}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-registry:8761/eureka
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # TTS Service
  tts-service:
    image: ghcr.io/aet-devops25/team-code-compass/tts-service:${IMAGE_TAG:-latest}
    container_name: flexfit-tts-service
    ports:
      - "8083:8083"
    depends_on:
      - service-registry
    networks:
      - flexfit-network
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-registry:8761/eureka
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/api/tts/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # GenAI Workout Worker
  genai-workout-worker:
    image: ghcr.io/aet-devops25/team-code-compass/genai-worker:${IMAGE_TAG:-latest}
    container_name: flexfit-genai-worker
    ports:
      - "8000:8000"
    networks:
      - flexfit-network
    environment:
      - OPEN_WEBUI_BASE_URL=${OPEN_WEBUI_BASE_URL:-https://gpu.aet.cit.tum.de}
      - CHAIR_API_KEY=${CHAIR_API_KEY}
      - MODEL_NAME=${MODEL_NAME:-llama3.3:latest}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Frontend
  frontend:
    image: ghcr.io/aet-devops25/team-code-compass/frontend:${IMAGE_TAG:-latest}
    container_name: flexfit-frontend
    ports:
      - "3000:80"
    depends_on:
      - api-gateway
    networks:
      - flexfit-network
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8080}
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

networks:
  flexfit-network:
    driver: bridge

volumes:
  postgres_data: