# This file overrides docker-compose.yml for local development
# It ensures we build locally instead of pulling from registry
version: '3.8'

services:
  service-registry:
    build: 
      context: ./server/service-registry
      dockerfile: Dockerfile
    
  api-gateway:
    build: 
      context: ./server/api-gateway
      dockerfile: Dockerfile
    
  user-service:
    build: 
      context: ./server/user-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    
  workout-plan-service:
    build: 
      context: ./server/workout-plan-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    
  genai-workout-worker:
    build: 
      context: ./genai
      dockerfile: Dockerfile
    
  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8080