global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "prometheus-alert-rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # FlexFit Spring Boot Services - using health endpoints for now
  - job_name: 'spring-boot-health'
    static_configs:
      - targets: ['host.docker.internal:8081', 'host.docker.internal:8082', 'host.docker.internal:8083']
    metrics_path: '/actuator/health'
    scrape_interval: 30s

  # FlexFit Spring Boot Services - Prometheus metrics
  - job_name: 'spring-boot-metrics'
    static_configs:
      - targets: ['host.docker.internal:8081', 'host.docker.internal:8082', 'host.docker.internal:8083']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s

  # TTS Service specific metrics
  - job_name: 'tts-service-metrics'
    static_configs:
      - targets: ['host.docker.internal:8083']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s 