spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # User service routes - handle /api/v1/users/** directly
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
        
        # Auth service routes - route /auth/** to user service
        - id: auth-service
          uri: lb://user-service
          predicates:
            - Path=/auth/**

        # Workout plan service routes - handle /api/v1/plans/** directly
        - id: workout-plan-service
          uri: lb://workout-plan-service
          predicates:
            - Path=/api/v1/plans/**

        # User service routes via service discovery path
        - id: user-service-discovery
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<segment>.*), /${segment}

        # Workout plan service routes via service discovery path
        - id: workout-plan-service-discovery
          uri: lb://workout-plan-service
          predicates:
            - Path=/workout-plan-service/**
          filters:
            - RewritePath=/workout-plan-service/(?<segment>.*), /${segment}

        # Direct Swagger UI access for user service
        - id: user-service-swagger-ui
          uri: lb://user-service
          predicates:
            - Path=/user-service/swagger-ui/**
          filters:
            - StripPrefix=1

        # Direct Swagger UI access for workout plan service
        - id: workout-plan-service-swagger-ui
          uri: lb://workout-plan-service
          predicates:
            - Path=/workout-plan-service/swagger-ui/**
          filters:
            - StripPrefix=1

        # API docs for user service
        - id: user-service-v3-api-docs
          uri: lb://user-service
          predicates:
            - Path=/user-service/v3/api-docs/**
          filters:
            - StripPrefix=1

        # API docs for workout plan service
        - id: workout-plan-service-v3-api-docs
          uri: lb://workout-plan-service
          predicates:
            - Path=/workout-plan-service/v3/api-docs/**
          filters:
            - StripPrefix=1

        # Swagger UI routes for easy access via gateway
        - id: user-service-docs
          uri: lb://user-service
          predicates:
            - Path=/docs/users/**
          filters:
            - StripPrefix=2
            - RewritePath=/docs/users/(?<remaining>.*), /${remaining}
            - AddRequestHeader=X-Forwarded-Host, localhost:8080
            - AddRequestHeader=X-Forwarded-Proto, http
            - AddRequestHeader=X-Forwarded-Prefix, /docs/users

        - id: workout-plan-service-docs
          uri: lb://workout-plan-service
          predicates:
            - Path=/docs/workout-plans/**
          filters:
            - StripPrefix=2
            - RewritePath=/docs/workout-plans/(?<remaining>.*), /${remaining}
            - AddRequestHeader=X-Forwarded-Host, localhost:8080
            - AddRequestHeader=X-Forwarded-Proto, http
            - AddRequestHeader=X-Forwarded-Prefix, /docs/workout-plans
            
        # API docs routes
        - id: user-service-api-docs
          uri: lb://user-service
          predicates:
            - Path=/docs/users/v3/api-docs/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=X-Forwarded-Host, localhost:8080
            - AddRequestHeader=X-Forwarded-Proto, http
            
        - id: workout-plan-service-api-docs
          uri: lb://workout-plan-service
          predicates:
            - Path=/docs/workout-plans/v3/api-docs/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=X-Forwarded-Host, localhost:8080
            - AddRequestHeader=X-Forwarded-Proto, http

      discovery:
        locator:
          enabled: false
          lower-case-service-id: true

server:
  port: ${PORT:8000}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway 