spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # User service routes - handle /api/v1/users/** directly
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**

        # User service routes via service discovery path
        - id: user-service-discovery
          uri: lb://user-service
          predicates:
            - Path=/user-service/api/v1/users/**
          filters:
            - RewritePath=/user-service/(?<segment>.*), /${segment}

        # Auth service routes - route /auth/** to user service
        - id: auth-service
          uri: lb://user-service
          predicates:
            - Path=/auth/**

        # Auth service routes via service discovery path
        - id: auth-service-discovery
          uri: lb://user-service
          predicates:
            - Path=/user-service/auth/**
          filters:
            - RewritePath=/user-service/(?<segment>.*), /${segment}

        - id: workout-plan-service
          uri: lb://workout-plan-service
          predicates:
            - Path=/api/workout-plans/**
          filters:
            - StripPrefix=1

        # Swagger UI routes for easy access via gateway
        - id: user-service-docs
          uri: lb://user-service
          predicates:
            - Path=/docs/users/**
          filters:
            - StripPrefix=2
            - RewritePath=/docs/users/(?<remaining>.*), /${remaining}
            - AddRequestHeader=X-Forwarded-Host, localhost:8000
            - AddRequestHeader=X-Forwarded-Proto, http
            - AddRequestHeader=X-Forwarded-Prefix, /docs/users

        - id: workout-plan-service-docs
          uri: lb://workout-plan-service
          predicates:
            - Path=/docs/workout-plans/**
          filters:
            - StripPrefix=2
            - RewritePath=/docs/workout-plans/(?<remaining>.*), /${remaining}
            - AddRequestHeader=X-Forwarded-Host, localhost:8000
            - AddRequestHeader=X-Forwarded-Proto, http
            - AddRequestHeader=X-Forwarded-Prefix, /docs/workout-plans

      discovery:
        locator:
          enabled: false
          lower-case-service-id: true

server:
  port: ${PORT:8000}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway 