# TUM Student Cluster specific values - DEVELOPMENT ENVIRONMENT
# Usage: source .env && envsubst < values-tum.yaml | helm install flexfit . -f - --namespace team-code-compass-development

# REQUIRED: Set your TUM ID here (from environment variable)
tumid: "${TUM_ID}"

# Secrets (from environment variables)
chairApiKey: "${CHAIR_API_KEY}"
postgres:
  password: "${POSTGRES_PASSWORD}"

# Use latest image tags from GHCR (most recent builds for development/staging)
serviceRegistry:
  image:
    tag: "${IMAGE_TAG}"

apiGateway:
  image:
    tag: "${IMAGE_TAG}"

userService:
  image:
    tag: "${IMAGE_TAG}"

workoutPlanService:
  image:
    tag: "${IMAGE_TAG}"

genaiWorker:
  image:
    tag: "${IMAGE_TAG}"

genaiWorkerLocal:
  image:
    tag: "${IMAGE_TAG}"

frontend:
  image:
    tag: "${IMAGE_TAG}"

# Enable monitoring stack
monitoring:
  prometheus:
    enabled: true
  grafana:
    enabled: true
    adminPassword: "${GRAFANA_ADMIN_PASSWORD:-admin}"
  alertmanager:
    enabled: true
  
  # Email alerts configuration
  alerts:
    email:
      enabled: true
      smtpHost: "${SMTP_HOST:-smtp.gmail.com:587}"
      from: "${ALERT_EMAIL_FROM:-hakanduranyt@gmail.com}"
      to: "${ALERT_EMAIL_TO:-hakanduranyt@gmail.com}"
      username: "${ALERT_EMAIL_USERNAME:-hakanduranyt@gmail.com}"
      password: "${ALERT_EMAIL_PASSWORD:-your_gmail_app_password_here}"

# TUM cluster specific ingress configuration
ingress:
  enabled: true
  className: "nginx"
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"