apiVersion: v1
kind: Config
clusters:
- name: "student"
  cluster:
    server: "https://rancher.ase.cit.tum.de/k8s/clusters/c-m-nhcfjg9h"

users:
- name: "student"
  user:
    token: "kubeconfig-u-disyfgjspqjvtbj:pz9h6kvj29czv2cxhdrmk8mt87pcdlkj6ttsttqswtlvs8dqmgbx5r"


contexts:
- name: "student"
  context:
    user: "student"
    cluster: "student"

current-context: "student"
